question_data = [
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In Dragon Ball Z, who was the first character to go Super Saiyan 2?", "correct_answer": "Gohan",
     "incorrect_answers": ["Goku", "Vegeta", "Trunks"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In the anime &quot;Mr. Osomatsu&quot;, how many brothers does Osomatsu-san have?",
     "correct_answer": "5", "incorrect_answers": ["6", "7", "4"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
     "question": "In &quot;Highschool of the Dead&quot;, where did Komuro and Saeko establish"
                 " to meet after the bus explosion?",
     "correct_answer": "Eastern Police Station",
     "incorrect_answers": ["The Center Mall", "Komuro&#039;s House", "On The Main Bridge"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following countries does &quot;JoJo&#039;s Bizarre Adventure:"
                 " Stardust Crusaders&quot; not take place in?",
     "correct_answer": "Philippines", "incorrect_answers": ["India", "Pakistan", "Egypt"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "Which one of these Manga titles was not created by Urasawa Naoki?",
     "correct_answer": "My Father&#039;s Journal", "incorrect_answers": ["Billy Bat", "20th Century Boys", "Monster"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
     "question": "The anime Attack on Titan was directed by Tetsuta Araki, the same person "
                 "who directed the anime Highschool of the Dead.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "In the anime Black Butler, who is betrothed to be married to Ciel Phantomhive?",
     "correct_answer": "Elizabeth Midford",
     "incorrect_answers": ["Rachel Phantomhive", "Alexis Leon Midford", "Angelina Dalles"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In the &quot;Toaru Majutsu no Index&quot; anime, Touma Kamijou is a level "
                 "0 esper that has the ability to do what?",
     "correct_answer": "Dispell any esper or magical powers",
     "incorrect_answers": ["Teleport", "Make telepathic communications", "Create electricity from his own body"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "What sport is being played in the Anime Eyeshield 21?", "correct_answer": "American Football",
     "incorrect_answers": ["Baseball", "Football", "Basketball"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
     "question": "In &quot;One Piece&quot;, who is the girl who overcame her enslaved past and "
                 "became an agent of an army to fight the corrupt government?",
     "correct_answer": "Koala", "incorrect_answers": ["Boa Hancock", "Nico Robin", "Emporio Ivankov "]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
     "question": "In the &quot;Dragon Ball&quot; franchise, what is the name of Goku&#039;s brother?",
     "correct_answer": "Raditz", "incorrect_answers": ["Gohan", "Vegeta", "Bardock"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In &quot;Toriko&quot;, which of the following foods is knowingly compatible with Toriko?",
     "correct_answer": "Poison Potato", "incorrect_answers": ["Mors Oil", "Alpacookie", "Parmesansho Fruit"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "What year did &quot;Bishoujo Senshi Sailor Moon&quot; air in Japan?", "correct_answer": "1992",
     "incorrect_answers": ["1989", "1990", "1994"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "hard",
     "question": "The &quot;To Love-Ru&quot; Manga was started in what year?", "correct_answer": "2006",
     "incorrect_answers": ["2007", "2004", "2005"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "In &quot;Highschool DxD&quot;, what is the name of the item some humans are born with?",
     "correct_answer": "Sacred Gear", "incorrect_answers": ["Imperial Arm", "Hallowed Relic", "Blessed Artifact"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "What was the reason for the banning of episode 35 of the &quot;Pok&eacute;mon "
                 "Original Series&quot; Anime?",
     "correct_answer": "Gun Usage", "incorrect_answers": ["Flashing Images", "Jynx", "Strong Violence"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "Which of these is not a world in the anime &quot;Buddyfight&quot;?",
     "correct_answer": "Ancient Dragon World",
     "incorrect_answers": ["Dragon World", "Star Dragon World", "Darkness Dragon World"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "What colour hair does the main character of the Yu-Gi-Oh! original anime series have?",
     "correct_answer": "Red, black and yellow",
     "incorrect_answers": ["Red, yellow and green", "Red, black and green", "Red, purple and blue"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "Which JoJo&#039;s Bizarre Adventure character possesses the Stand named Silver Chariot?",
     "correct_answer": "Jean Pierre Polnareff",
     "incorrect_answers": ["Noriaki Kakyoin", "Hol Horse", "Hermes Costello"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "The protagonist in &quot;Humanity Has Declined&quot; has no discernable name"
                 " and is simply referred to as &#039;I&#039; for most of the series.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "medium",
     "question": "Which studio made Cowboy Bebop?", "correct_answer": "Sunrise",
     "incorrect_answers": ["Bones", "Madhouse", "Pierriot"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple", "difficulty": "easy",
     "question": "In the Naruto manga, what is the last name of Tsunade?", "correct_answer": "Senju",
     "incorrect_answers": ["Haruno", "Uzumaki", "Yamanaka"]}

]
